version: '3.8'

services:

  postgres:
    image: postgres:15-alpine
    container_name: hostelnet-allocation-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hostelnet
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hostelnet-network

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: hostelnet-zookeeper
    ports:
      - "2181:2181"
    networks:
      - hostelnet-network

  kafka:
    image: wurstmeister/kafka
    container_name: hostelnet-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://hostelnet-kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: hostelnet-zookeeper:2181
      KAFKA_CREATE_TOPICS: "user-events:1:1" # Auto-create topic
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - hostelnet-network

volumes:
  postgres_data:


networks:
  hostelnet-network:
    driver: bridge
